```yaml
    version: '3.8'

    services:
      backend:
        build:
          context: .
          dockerfile: packages/backend/Dockerfile
        ports:
          - "3001:3001"
        environment:
          - NODE_ENV=development
          - DB_HOST=timescaledb
          - RABBITMQ_HOST=rabbitmq
        depends_on:
          - timescaledb
          - rabbitmq

      frontend:
        build:
          context: .
          dockerfile: packages/frontend/Dockerfile
        ports:
          - "3000:3000"
        environment:
          - NEXT_PUBLIC_API_URL=http://localhost:3001

      timescaledb:
        image: timescale/timescaledb:latest-pg14
        ports:
          - "5432:5432"
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=memecoin
        volumes:
          - timescaledb_data:/var/lib/postgresql/data

      rabbitmq:
        image: rabbitmq:3-management
        ports:
          - "5672:5672"
          - "15672:15672"
        environment:
          - RABBITMQ_DEFAULT_USER=guest
          - RABBITMQ_DEFAULT_PASS=guest

    volumes:
      timescaledb_data:

    ```
